import Navbar from "@/components/Navbar/Navbar";
import AuthProvider from "@/Context/auth";
import ChatbotProvider from "@/Context/chatbot";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ChatbotProvider>
          <Navbar/>
          {children}
          </ChatbotProvider>
        
        </AuthProvider>
      </body>
    </html>
  );
}
